spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: y6Xk9v2yM9m4Gf1mA8pQ0JxCk6f9Q2wE1Rr7Zx0M5A8=
  expiration: 3600000   # 1 hour (ms)	

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: account-service   # change per service
