spring:
    application:
        name: transaction-service

    datasource:
        url: jdbc:postgresql://localhost:5432/accountdb
        username: postgres
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
  port: 8083
  
resilience4j:
    circuitbreaker:
        instances:
            accountService:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 10s

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: false

jwt:
    secret: y6Xk9v2yM9m4Gf1mA8pQ0JxCk6f9Q2wE1Rr7Zx0M5A8=
